import { Inter } from "next/font/google";
import "./globals.scss";
import { Providers } from "./providers";
import NavigationBar from "@/components/common/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <NavigationBar />
          <main className="wrapper">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
